#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
schema=$3
host=$4
port=$5
hostpath=$6

#sudo yunohost app checkurl $domain:$port$host_path -a reverseproxy
#if [[ ! $? -eq 0 ]]; then
#  exit 1
#fi

# Remove trailing "/" for next commands
path=${path%/}

# Configure Nginx and reload
sed -i "s@SCHEMATOCHANGE@$schema@g" ../conf/nginx.conf
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@HOSTTOCHANGE@$host@g" ../conf/nginx.conf
sed -i "s@PORTTOCHANGE@$port@g" ../conf/nginx.conf
sed -i "s@HOSTPATHTOCHANGE@$hostpath@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/reverseproxy.conf
sudo service nginx reload
echo $?
