#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
scheme=$3
host=$4
port=$5
remotepath=$6
includefile=$7
is_public=$8

sudo yunohost app checkurl $domain$path -a reverseproxy
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

if [ "$includefile" != "" ];then
	includefile="include						$includefile"
fi

# Remove trailing "/" for next commands
path=${path%/}

# Configure Nginx and reload
sed -i "s@SCHEMETOCHANGE@$scheme@g" ../conf/nginx.conf
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@HOSTTOCHANGE@$host@g" ../conf/nginx.conf
sed -i "s@PORTTOCHANGE@$port@g" ../conf/nginx.conf
sed -i "s@REMOTEPATH@$remotepath@g" ../conf/nginx.conf
sed -i "s@INCLUDEFILE@$includefile@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/reverseproxy.conf

# Make app public if necessary
sudo yunohost app setting reverseproxy is_public -v "$is_public"
if [ "$is_public" = "Yes" ]; then
    sudo yunohost app setting reverseproxy skipped_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
